#******************makefile*******************
#        Author: Tim 15291418231@163.com
#        Create: 2018-10-03 11:52:59
# Last Modified: 2018-10-03 11:52:59
#**********************************************/

test.out:test.c Heap.c
	gcc -g Heap.c test.c -o test.out


.PHONY:clean
clean:
	rm -rf test.out

