#******************makefile*******************
#        Author: Tim 15291418231@163.com
#        Create: 2018-10-03 10:05:13
# Last Modified: 2018-10-03 10:05:13
#**********************************************/
test.out:main.c
	gcc main.c -o test.out


.PHONY:clean
clean:
	rm -rf test.out

